# Generated by Django 5.2.1 on 2026-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeDistrict',
            fields=[
                ('legis_dist', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('collected_signatures', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6)),
                ('partners', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_mobilized', models.BooleanField(default=False)),
                ('registered_voters', models.IntegerField(editable=False)),
                ('geometry', models.JSONField(editable=False)),
            ],
        ),
    ]
