# Generated by Django 5.2.1 on 2026-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislativedistrict',
            options={'verbose_name': 'Legislative District', 'verbose_name_plural': 'Legislative Districts'},
        ),
        migrations.AlterField(
            model_name='legislativedistrict',
            name='geometry',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='legislativedistrict',
            name='legis_dist',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='legislativedistrict',
            name='registered_voters',
            field=models.IntegerField(),
        ),
    ]
