# Generated by Django 5.2.1 on 2026-07-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0002_alter_legislativedistrict_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativedistrict',
            name='geometry',
        ),
    ]
