# Generated by Django 5.2.1 on 2026-07-06 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0003_remove_legislativedistrict_geometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislativedistrict',
            options={'verbose_name': 'legislative_district', 'verbose_name_plural': 'legislative_districts'},
        ),
        migrations.AlterField(
            model_name='legislativedistrict',
            name='collected_signatures',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='legislativedistrict',
            name='registered_voters',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
