# Generated by Django 5.2.1 on 2026-07-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0004_alter_legislativedistrict_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativedistrict',
            name='collected_signatures',
            field=models.IntegerField(),
        ),
    ]
